# Generated by Django 5.2 on 2025-05-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntispamDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, unique=True, verbose_name='Word')),
                ('value', models.SmallIntegerField(verbose_name='Value')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Time msg')),
                ('full_time', models.CharField(max_length=128, verbose_name='Time msg')),
                ('text', models.TextField(verbose_name='Text')),
                ('chat_id', models.BigIntegerField(verbose_name='Chat id')),
                ('msg_id', models.BigIntegerField(verbose_name='Msg id')),
                ('user_id', models.BigIntegerField(verbose_name='User id')),
                ('sum_spam', models.SmallIntegerField(verbose_name='Sum spam')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
