# Generated by Django 5.1.1 on 2024-12-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
        ('personal', '0002_operator_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Executor', to='personal.operator'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='new', max_length=32, verbose_name='Status'),
        ),
    ]
