# Generated by Django 5.1.1 on 2024-12-17 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_application_executor_application_status'),
        ('personal', '0002_operator_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Signer', to='personal.operator'),
        ),
    ]
