# Generated by Django 5.1.1 on 2024-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_application_signer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='report_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Report message id'),
        ),
    ]
