# Generated by Django 5.1.1 on 2024-12-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_application_report_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title btn')),
                ('type', models.CharField(blank=True, default='category', max_length=32, null=True, verbose_name='Type btn')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Order btn')),
                ('size', models.CharField(blank=True, default='small', max_length=16, null=True, verbose_name='Size btn')),
                ('departament', models.CharField(blank=True, max_length=32, null=True, verbose_name='Departament')),
                ('layout', models.CharField(blank=True, max_length=16, null=True, verbose_name='Layout category')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
