# Generated by Django 5.1.1 on 2024-12-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='problems',
            field=models.ManyToManyField(blank=True, to='helpdesk.button'),
        ),
    ]
