# Generated by Django 5.1.1 on 2024-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_button_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='layout',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Layout'),
        ),
        migrations.AddField(
            model_name='application',
            name='step',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Step'),
        ),
    ]
