# Generated by Django 5.1.1 on 2025-01-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_application_owner_tg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='user_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_tag',
        ),
    ]
