# Generated by Django 5.1.1 on 2025-01-31 16:56

import config.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='media',
            field=models.FileField(storage=config.utilities.UUIDFileStorage(), upload_to='website/vacancy'),
        ),
    ]
