# Generated by Django 5.1.1 on 2025-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
