# Generated by Django 5.1.1 on 2024-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Tg user id'),
        ),
    ]
