# Generated by Django 5.1.1 on 2024-12-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_operator_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='tg_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Tg user id'),
        ),
    ]
