# Generated by Django 5.1.1 on 2024-12-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_operator_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='departament',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Departament'),
        ),
    ]
