# Generated by Django 5.1.1 on 2025-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_operator_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='operator',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Telephone'),
        ),
    ]
