# Generated by Django 5.1.1 on 2025-04-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_operator_email_operator_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='First name user')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Last name user')),
                ('user_tag', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tag user')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='User id')),
                ('group_id', models.BigIntegerField(blank=True, null=True, verbose_name='Group id')),
                ('is_check', models.BooleanField(default=False, verbose_name='Is check user')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Date of updating')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
