# Generated by Django 5.1.1 on 2025-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='User id'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='user_tag',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Tag user'),
        ),
    ]
